"""Module for utility functions for working with Avocado stubs."""

from __future__ import annotations

import pickle as pkl
import re
from dataclasses import dataclass
from pathlib import Path
from typing import cast

AVOCADO_FUNCTION_PREFIX = "_avocado_"
AVOCADO_STUB_DIR = "verification/cbmc_stubs"

# This is generated by `generate_avocado_stubs.py`
DEFAULT_STUB_MAPPINGS = f"{AVOCADO_STUB_DIR}/c_stub_rename_map.pkl"


@dataclass(frozen=True)
class RenameData:
    """Metadata for renaming functions in libraries defined in the ANSI-C standard to Avocado stubs.

    The CBMC verifier includes its own copy of stub functions in libraries defined in the ANSI-C
    standard that it uses for verifying client code that makes use them. This can sometimes lead to
    unexpected issues related to internal C functions that are used by its copy of stub functions:

        https://github.com/diffblue/cbmc/issues/8844

    Avocado stubs aim to mitigate this issue by ensuring only the functions directly in the copy of
    the standard library are used. However, standard library functions cannot be defined twice,
    and so each function (i.e., stub) is prepended with `avocado_` to avoid naming collisions.


    See `generate_avocado_stubs.py` for how Avocado stubs are generated.

    Attributes:
        renamed_identifier (str): The function's name as an Avocado stub.
        file_path (Path): The path to the CBMC stub file in which the function is defined.
    """

    renamed_identifier: str
    file_path: Path


def apply_stub_renaming(file_content: str) -> str:
    """Return the file content after stub function replacements have been applied.

    Args:
        file_content (str): The content of the file to which to apply renaming.

    Returns:
        str: The file content after stub function replacements have been applied.
    """
    file_content_with_renaming = file_content
    for original_identifier, rename_metadata in get_stub_mappings().items():
        # Don't replace identifiers twice (i.e., replace only exact matches)
        name_to_replace_pattern = r"\b" + original_identifier + r"\b"
        file_content_with_renaming = re.sub(
            name_to_replace_pattern, rename_metadata.renamed_identifier, file_content_with_renaming
        )
    return file_content_with_renaming


def get_stub_mappings(
    path_to_stub_mappings: str = DEFAULT_STUB_MAPPINGS,
) -> dict[str, RenameData]:
    """Return the stub mappings for Avocado stubs for functions declared in the ANSI-C standard.

    Args:
        path_to_stub_mappings (str, optional): Path to stub mappings. Defaults to
            DEFAULT_STUB_MAPPINGS.

    Returns:
        dict[str, RenameData]: A mapping from the original C function identifier to rename data.
    """
    with Path(path_to_stub_mappings).open(mode="rb") as f:
        data = pkl.load(f)
        return cast("dict[str, RenameData]", data)
