"""Classes for working with Avocado stubs."""

from __future__ import annotations

import pickle as pkl
import re
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import cast

from util.tree_sitter_util import IdentifierNodeParentType

AVOCADO_FUNCTION_PREFIX = "_avocado_"
AVOCADO_STUB_DIR = "verification/cbmc_stubs"


@dataclass(frozen=True)
class RenameResult:
    """Class representing the result of a rename operation.

    Attributes:
        src_after_renaming (str): The C source code after renaming.
        avocado_stubs (list[Path]): The path(s) to the Avocado stub(s) that define the re-named
            functions.
    """

    src_after_renaming: str
    avocado_stubs: list[Path]

    def get_headers(self) -> list[str]:
        """Return the name of the header files that define the functions that have been renamed.

        Returns:
            list[str]: The name of the header files that defined the functions that have been
                renamed.
        """
        return [stub_file_path.name.replace(".c", ".h") for stub_file_path in self.avocado_stubs]

    def get_stub_file_paths(self, default_headers: list[str]) -> list[str]:
        """Return the path(s) to the stub files used by Avocado for verification.

        The stub files used by Avocado for verification should not take precedence over the default
        headers and stubs used by CBMC, internally.

        Args:
            default_headers (list[str]): The default headers to check the stub files against.

        Returns:
            list[str]: The path(s) to the stub files used by Avocado for verification.
        """
        return [
            str(stub_file_path)
            for stub_file_path in self.avocado_stubs
            if stub_file_path.name.replace(".c", ".h") not in default_headers
        ]


# This is generated by `generate_avocado_stubs.py`
DEFAULT_STUB_MAPPINGS = f"{AVOCADO_STUB_DIR}/c_stub_rename_map.pkl"


@dataclass(frozen=True)
class RenameData:
    """Data for renaming functions in libraries defined in the ANSI-C standard to Avocado stubs.

    The CBMC verifier includes its own copy of stub functions in libraries defined in the ANSI-C
    standard that it uses for verifying client code that makes use them. This can lead to
    issues related to internal C functions that are used by its copy of stub functions:

        https://github.com/diffblue/cbmc/issues/8844

    Avocado stubs aim to mitigate this issue by ensuring only the functions directly in the copy of
    the standard library are used. However, standard library functions cannot be defined twice,
    and so each function (i.e., stub) is prepended with `avocado_` to avoid naming collisions.


    See `generate_avocado_stubs.py` for how Avocado stubs are generated.

    Attributes:
        renamed_identifier (str): The function's name as an Avocado stub.
        parent_node_type (IdentifierNodeParentTYpe): The type of the nearest parent declaration node
            of the renamed identifier.
        file_path (Path): The path to the CBMC stub file in which the function is defined.
    """

    renamed_identifier: str
    parent_node_type: IdentifierNodeParentType
    file_path: Path


class AvocadoIdentifierRenamer:
    """Class for applying renaming (i.e., ANSI-C identifier -> Avocado identifiers) in C files.

    Attributes:
        _ansi_id_to_rename_data (dict[str, list[RenameData]]): Map from ANSI-C library function
            identifier(s) to their renamed Avocado identifiers. See: `RenameData` class above.
    """

    _ansi_id_to_rename_data: dict[str, list[RenameData]]

    # This is generated by `generate_avocado_stubs.py`
    DEFAULT_STUB_MAPPINGS = f"{AVOCADO_STUB_DIR}/c_stub_rename_map.pkl"

    def __init__(self, path_to_stub_mappings: Path = Path(DEFAULT_STUB_MAPPINGS)) -> None:
        """Create a new AvocadoIdentifierRenamer."""
        try:
            data = pkl.load(path_to_stub_mappings.open(mode="rb"))
            self._ansi_id_to_rename_data = cast("dict[str, list[RenameData]]", data)
        except Exception as e:
            msg = f"Failed to load Avocado stub mappings from: {path_to_stub_mappings}"
            raise ValueError(msg) from e

    def rename_ansi_identifiers_to_avocado_identifiers(self, file_content: str) -> RenameResult:
        """Return the rename result after ANSI library function ids are replaced with Avocado ids.

        Args:
            file_content (str): The content of the file to which to apply renaming.

        Returns:
            str: The rename result after ANSI library functions have been renamed.
        """
        file_content_with_renaming = file_content
        avocado_stub_files_to_use = set()
        for original_identifier, rename_metadata in self._ansi_id_to_rename_data.items():
            # Don't replace identifiers twice (i.e., replace only exact matches)
            renamed_identifier = self.get_renamed_identifier(original_identifier, rename_metadata)
            name_to_replace_pattern = r"\b" + original_identifier + r"\b"
            file_content_with_renaming, count = re.subn(
                name_to_replace_pattern,
                renamed_identifier,
                file_content_with_renaming,
            )
            if count > 0:
                rename_data_for_definition = self.get_rename_data_for_file_containing_definition(
                    original_identifier, rename_metadata
                )
                avocado_stub_files_to_use.add(rename_data_for_definition.file_path)

        return RenameResult(file_content_with_renaming, list(avocado_stub_files_to_use))

    def get_identifier_mapping(self) -> MappingProxyType[str, str]:
        """Return the mapping from ANSI-C identifiers to Avocado identifiers.

        Returns:
            MappingProxyType[str, list[RenameData]]: The mapping from ANSI-C identifiers to Avocado
                rename data.
        """
        return MappingProxyType(
            {
                original_identifier: self.get_renamed_identifier(original_identifier, rename_data)
                for original_identifier, rename_data in self._ansi_id_to_rename_data.items()
            }
        )

    def get_renamed_identifier(
        self, original_identifier: str, rename_data: list[RenameData]
    ) -> str:
        """Return the renamed identifier corresponding to the original identifier.

        Args:
            original_identifier (str): The original identifier, pre-renaming.
            rename_data (list[RenameData]): The rename data from which to get the renamed
                identifier.

        Returns:
            str: The renamed identifier.
        """
        renamed_identifiers = {rename.renamed_identifier for rename in rename_data}
        if len(renamed_identifiers) > 1:
            msg = (
                f"Expected exactly one renaming for {original_identifier}, "
                f"but got {renamed_identifiers}"
            )
            raise ValueError(msg)
        return next(iter(renamed_identifiers))

    def get_rename_data_for_file_containing_definition(
        self, original_identifier: str, rename_metadata: list[RenameData]
    ) -> RenameData:
        """Return the rename data corresponding to the definition of an identifier.

        It is the case that rename data for an identifier can correspond to where it is declared
        (i.e., a function prototype), defined (i.e., the function definition), or a call
        (i.e., a call expression).

        This returns the rename data for where the identifier is defined.

        Args:
            original_identifier (str): The identifier for which to return the rename data.
            rename_metadata (list[RenameData]): The rename metadata for the given identifier.

        Returns:
            RenameData: The rename data for where the identifier is defined.
        """
        rename_data_for_definition = [
            data
            for data in rename_metadata
            if data.parent_node_type == IdentifierNodeParentType.FUNCTION_DEFINITION
        ]
        if len(rename_data_for_definition) > 1:
            msg = (
                f"Expected a single definition for '{original_identifier}', "
                f"but got {rename_data_for_definition}"
            )
            raise ValueError(msg)
        return rename_data_for_definition[0]


def apply_stub_renaming(file_content: str) -> str:
    """Return the file content after stub function replacements have been applied.

    Args:
        file_content (str): The content of the file to which to apply renaming.

    Returns:
        str: The file content after stub function replacements have been applied.
    """
    file_content_with_renaming = file_content
    original_identifiers_to_rename_data = get_stub_mappings()
    for original_identifier, rename_data in original_identifiers_to_rename_data.items():
        # Don't replace identifiers twice (i.e., replace only exact matches)
        name_to_replace_pattern = r"\b" + original_identifier + r"\b"
        renamed_identifier = get_renamed_identifier(original_identifier, rename_data)
        if renamed_identifier in original_identifiers_to_rename_data:
            msg = (
                f"A renamed identifier was the same as an original identifier: "
                f"'{renamed_identifier}'"
            )
            raise ValueError(msg)
        file_content_with_renaming = re.sub(
            name_to_replace_pattern, renamed_identifier, file_content_with_renaming
        )
    return file_content_with_renaming


def get_stub_mappings(
    path_to_stub_mappings: str = DEFAULT_STUB_MAPPINGS,
) -> dict[str, list[RenameData]]:
    """Return the stub mappings for Avocado stubs for functions declared in the ANSI-C standard.

    Args:
        path_to_stub_mappings (str, optional): Path to pickled stub mappings. Defaults to
            DEFAULT_STUB_MAPPINGS.

    Returns:
        dict[str, list[RenameData]]: A mapping from the original C function identifier to rename
            data.
    """
    with Path(path_to_stub_mappings).open(mode="rb") as f:
        data = pkl.load(f)
        return cast("dict[str, list[RenameData]]", data)


def get_renamed_identifier(original_identifier: str, rename_data: list[RenameData]) -> str:
    """Return the renamed identifier corresponding to the original identifier.

    Args:
        original_identifier (str): The original identifier, pre-renaming.
        rename_data (list[RenameData]): The rename data from which to get the renamed identifier.

    Returns:
        str: The renamed identifier.
    """
    renamed_identifiers = {rename.renamed_identifier for rename in rename_data}
    if len(renamed_identifiers) != 1:
        msg = (
            f"Expected exactly one renaming for {original_identifier}, "
            f"but got {renamed_identifiers}"
        )
        raise ValueError(msg)
    return next(iter(renamed_identifiers))
