"""Module for utility functions for working with Avocado stubs."""

from __future__ import annotations

import pickle as pkl
import re
from dataclasses import dataclass
from pathlib import Path
from typing import cast

import tree_sitter_c as tsc
from tree_sitter import Language, Parser

from util.tree_sitter_util import IdentifierNodeParentType, get_function_identifiers

AVOCADO_FUNCTION_PREFIX = "_avocado_"
_TREE_SITTER_LANG = Language(tsc.language())
_PARSER = Parser(_TREE_SITTER_LANG)
AVOCADO_STUB_DIR = "verification/cbmc_stubs"
C_KEYWORD_FILE_PATH = f"{AVOCADO_STUB_DIR}/c_keywords.txt"

# This is generated by `generate_avocado_stubs.py`
DEFAULT_STUB_MAPPINGS = f"{AVOCADO_STUB_DIR}/c_stub_rename_map.pkl"


@dataclass(frozen=True)
class RenameData:
    """Data for renaming functions in libraries defined in the ANSI-C standard to Avocado stubs.

    The CBMC verifier includes its own copy of stub functions in libraries defined in the ANSI-C
    standard that it uses for verifying client code that makes use them. This can lead to
    issues related to internal C functions that are used by its copy of stub functions:

        https://github.com/diffblue/cbmc/issues/8844

    Avocado stubs aim to mitigate this issue by ensuring only the functions directly in the copy of
    the standard library are used. However, standard library functions cannot be defined twice,
    and so each function (i.e., stub) is prepended with `avocado_` to avoid naming collisions.


    See `generate_avocado_stubs.py` for how Avocado stubs are generated.

    Attributes:
        renamed_identifier (str): The function's name as an Avocado stub.
        parent_node_type (IdentifierNodeParentTYpe): The type of the nearest parent declaration node
            of the renamed identifier.
        file_path (Path): The path to the CBMC stub file in which the function is defined.
    """

    renamed_identifier: str
    parent_node_type: IdentifierNodeParentType
    file_path: Path


def apply_stub_renaming(file_content: str) -> str:
    """Return the file content after stub function replacements have been applied.

    Args:
        file_content (str): The content of the file to which to apply renaming.

    Returns:
        str: The file content after stub function replacements have been applied.
    """
    file_content_with_renaming = file_content
    original_identifiers_to_rename_data = get_stub_mappings()
    for original_identifier, rename_data in original_identifiers_to_rename_data.items():
        # Don't replace identifiers twice (i.e., replace only exact matches)
        name_to_replace_pattern = r"\b" + original_identifier + r"\b"
        renamed_identifier = get_renamed_identifier(original_identifier, rename_data)
        if renamed_identifier in original_identifiers_to_rename_data:
            msg = (
                f"A renamed identifier was the same as an original identifier: "
                f"'{renamed_identifier}'"
            )
            raise ValueError(msg)
        file_content_with_renaming = re.sub(
            name_to_replace_pattern, renamed_identifier, file_content_with_renaming
        )
    return file_content_with_renaming


def get_stub_mappings(
    path_to_stub_mappings: str = DEFAULT_STUB_MAPPINGS,
) -> dict[str, list[RenameData]]:
    """Return the stub mappings for Avocado stubs for functions declared in the ANSI-C standard.

    Args:
        path_to_stub_mappings (str, optional): Path to pickled stub mappings. Defaults to
            DEFAULT_STUB_MAPPINGS.

    Returns:
        dict[str, list[RenameData]]: A mapping from the original C function identifier to rename
            data.
    """
    with Path(path_to_stub_mappings).open(mode="rb") as f:
        data = pkl.load(f)
        return cast("dict[str, list[RenameData]]", data)


def get_renamed_identifier(original_identifier: str, rename_data: list[RenameData]) -> str:
    """Return the renamed identifier corresponding to the original identifier.

    Args:
        original_identifier (str): The original identifier, pre-renaming.
        rename_data (list[RenameData]): The rename data from which to get the renamed identifier.

    Returns:
        str: The renamed identifier.
    """
    renamed_identifiers = {rename.renamed_identifier for rename in rename_data}
    if len(renamed_identifiers) != 1:
        msg = (
            f"Expected exactly one renaming for {original_identifier}, "
            f"but got {renamed_identifiers}"
        )
        raise ValueError(msg)
    return next(iter(renamed_identifiers))


def get_stub_implementation(original_identifier: str, header_name: str) -> str | None:
    r"""Return the implementation of the Avocado stub for the given function, or None if not found.

    Looks up the function whose identifier in the stub file is
    ``_avocado_<original_identifier>`` and returns the full function definition as a string with
    the `_avocado_` prefix removed.


    Args:
        original_identifier (str): The original C function identifier (without the Avocado prefix).
        header_name (str): The name of the header file (e.g. "string.h") whose corresponding
            stub file should be searched.

    Returns:
        str | None: The full function definition text, or `None` if the stub file does not exist
            or the function is not found in the stub file.
    """
    expected_path_to_stub_file = Path(f"{AVOCADO_STUB_DIR}/{header_name.replace('.h', '.c')}")
    if not expected_path_to_stub_file.exists():
        return None

    file_content = expected_path_to_stub_file.read_text(encoding="utf-8")
    tree = _PARSER.parse(bytes(file_content, encoding="utf-8"))

    avocado_identifier = AVOCADO_FUNCTION_PREFIX + original_identifier
    definition = None
    for identifier_node, parent_type in get_function_identifiers(tree.root_node):
        if (
            parent_type == IdentifierNodeParentType.FUNCTION_DEFINITION
            and identifier_node.text is not None
            and identifier_node.text.decode() == avocado_identifier
        ):
            # Walk up to the function_definition node to get the full definition text.
            definition_node = identifier_node.parent
            while definition_node is not None and definition_node.type != "function_definition":
                definition_node = definition_node.parent
            if definition_node is not None:
                definition = file_content[definition_node.start_byte : definition_node.end_byte]
    if definition:
        return definition.replace(AVOCADO_FUNCTION_PREFIX, "")
    return None
